FROM adminer:latest

USER root

# Store PHP Configs at /usr/local/etc/php/conf.d
RUN echo "upload_max_filesize = 500M" >> /etc/php/7.4/cli/php.ini \
    && echo "post_max_size = 500M"       >> /etc/php/7.4/cli/php.ini \
    && echo "memory_limit = -1"           >> /etc/php/7.4/cli/php.ini \
    && echo "max_execution_time = 0"      >> /etc/php/7.4/cli/php.ini

VOLUME /sessions

USER adminer

EXPOSE 8080