version: "3.9"

services:
  api:
    image: gigz-api

    build: .
    container_name: gigz-api

    restart: always
    command: yarn dev

    ports:
      - 3000:3000

    env_file: .env

    volumes:
      - ./src:/usr/src/app/src

    depends_on:
      - db

  adminer:
    image: adminer
    container_name: gigz-adminer

    restart: always

    ports:
      - 5555:8080

  db:
    image: mysql:8.0
    container_name: gigz-database

    restart: always

    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gigz

    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:
