up *FLAGS:
    docker compose up {{FLAGS}}

down:
    docker compose down

build SERVICE *FLAGS:
    docker compose build {{SERVICE}} {{FLAGS}}

logs SERVICE *FLAGS:
    docker compose logs {{SERVICE}} {{FLAGS}}

exec +COMMAND:
    docker compose exec api {{COMMAND}}

shell SERVICE SHELL='bash':
    docker compose exec -it {{SERVICE}} {{SHELL}}

fetch URL *FLAGS:
    httpx http://localhost:3000/api/{{URL}} {{FLAGS}}

prisma +COMMAND:
    docker compose exec api yarn prisma {{COMMAND}}

migrate:
    docker compose exec api yarn prisma migrate dev
