up *FLAGS:
    docker compose up {{FLAGS}}

down:
    docker compose down

build SERVICE *FLAGS:
    docker compose build {{SERVICE}} {{FLAGS}}

logs SERVICE *FLAGS:
    docker compose logs {{SERVICE}} {{FLAGS}}

exec +COMMAND:
    docker compose exec api {{COMMAND}}

shell SERVICE SHELL='bash':
    docker compose exec -it {{SERVICE}} {{SHELL}}
