name: Build for mobile
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'front/.tool-versions'
      - run: npm ci
      - run: npm run build
