name: Deploy to production
on:
  workflow_dispatch:
jobs:
  build:
    name: Build & deploy to server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
    - uses: actions/checkout@v3

    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "back/src/, back/prisma/, back/Dockerfile, back/package.json, back/yarn.lock, back/tsconfig.json"
        target: .

    - name: Build the docker image and Deploy it
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd back/ 
          docker compose down
          docker compose up --build
          docker compose exec api yarn prisma migrate dev
